---
# tasks file for nginx

- name: Install epel release
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Start nginx
  command: systemctl start nginx
  tags:
    - skip_ansible_lint
